# CMake generated Testfile for 
# Source directory: /home/xx/EdgeVoiceRAG
# Build directory: /home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(edge_voice_rag_unit_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/unit_tests")
set_tests_properties(edge_voice_rag_unit_tests PROPERTIES  WORKING_DIRECTORY "/home/xx/EdgeVoiceRAG" _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;771;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(multi_level_response_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/multi_level_response_tests")
set_tests_properties(multi_level_response_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;775;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(edge_response_backend_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/edge_response_backend_tests")
set_tests_properties(edge_response_backend_tests PROPERTIES  WORKING_DIRECTORY "/home/xx/EdgeVoiceRAG" _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;779;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(llm_protocol_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/llm_protocol_tests")
set_tests_properties(llm_protocol_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;783;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(llm_service_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/llm_service_tests")
set_tests_properties(llm_service_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;787;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(llm_backend_factory_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/llm_backend_factory_tests")
set_tests_properties(llm_backend_factory_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;791;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(llm_backend_stream_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/llm_backend_stream_tests")
set_tests_properties(llm_backend_stream_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;795;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(llm_stream_service_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/llm_stream_service_tests")
set_tests_properties(llm_stream_service_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;799;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(llm_control_server_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/llm_control_server_tests")
set_tests_properties(llm_control_server_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;803;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(rag_stream_protocol_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/rag_stream_protocol_tests")
set_tests_properties(rag_stream_protocol_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;807;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(rag_stream_client_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/rag_stream_client_tests")
set_tests_properties(rag_stream_client_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;811;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(streaming_answer_backend_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/streaming_answer_backend_tests")
set_tests_properties(streaming_answer_backend_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;815;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(streaming_sentence_buffer_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/streaming_sentence_buffer_tests")
set_tests_properties(streaming_sentence_buffer_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;819;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(voice_assistant_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/voice_assistant_tests")
set_tests_properties(voice_assistant_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;823;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(bounded_blocking_queue_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/bounded_blocking_queue_tests")
set_tests_properties(bounded_blocking_queue_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;827;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(rag_control_protocol_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/rag_control_protocol_tests")
set_tests_properties(rag_control_protocol_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;831;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(rag_control_client_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/rag_control_client_tests")
set_tests_properties(rag_control_client_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;835;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(voice_input_pipeline_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/voice_input_pipeline_tests")
set_tests_properties(voice_input_pipeline_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;839;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(continuous_voice_session_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/continuous_voice_session_tests")
set_tests_properties(continuous_voice_session_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;843;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(voice_performance_report_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/voice_performance_report_tests")
set_tests_properties(voice_performance_report_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;847;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(wav_audio_reader_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/wav_audio_reader_tests")
set_tests_properties(wav_audio_reader_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;851;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(local_rag_llm_backend_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/local_rag_llm_backend_tests")
set_tests_properties(local_rag_llm_backend_tests PROPERTIES  WORKING_DIRECTORY "/home/xx/EdgeVoiceRAG" _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;855;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(chinese_text_tokenizer_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/chinese_text_tokenizer_tests")
set_tests_properties(chinese_text_tokenizer_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;859;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(bm25_retriever_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/bm25_retriever_tests")
set_tests_properties(bm25_retriever_tests PROPERTIES  WORKING_DIRECTORY "/home/xx/EdgeVoiceRAG" _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;863;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(dense_vector_index_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/dense_vector_index_tests")
set_tests_properties(dense_vector_index_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;872;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(hybrid_retriever_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/hybrid_retriever_tests")
set_tests_properties(hybrid_retriever_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;876;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(retriever_runtime_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/retriever_runtime_tests" "/home/xx/EdgeVoiceRAG/vector_db/chunks.json" "/home/xx/EdgeVoiceRAG/models/embedding/bge-small-zh-v1.5" "/home/xx/EdgeVoiceRAG/vector_db/bge-small-zh-v1.5")
set_tests_properties(retriever_runtime_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;880;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(knowledge_base_loader_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/knowledge_base_loader_tests" "/home/xx/EdgeVoiceRAG/vector_db/chunks.json")
set_tests_properties(knowledge_base_loader_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;888;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(relevance_filtering_retriever_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/relevance_filtering_retriever_tests")
set_tests_properties(relevance_filtering_retriever_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;894;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(board_app_config_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/board_app_config_tests" "/home/xx/EdgeVoiceRAG/config/board_wsl.conf")
set_tests_properties(board_app_config_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;898;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
add_test(file_fingerprint_tests "/home/xx/EdgeVoiceRAG/build-board-pc-DEDGE_ENABLE_BGE_EMBEDDER=ON/file_fingerprint_tests")
set_tests_properties(file_fingerprint_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/xx/EdgeVoiceRAG/CMakeLists.txt;904;add_test;/home/xx/EdgeVoiceRAG/CMakeLists.txt;0;")
